const USERS = [
  {
    "login": "A",
    "id": 1410106,
    "node_id": "MDQ6VXNlcjE0MTAxMDY=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/1410106?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/A",
    "html_url": "https://github.com/A",
    "followers_url": "https://api.github.com/users/A/followers",
    "following_url": "https://api.github.com/users/A/following{/other_user}",
    "gists_url": "https://api.github.com/users/A/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/A/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/A/subscriptions",
    "organizations_url": "https://api.github.com/users/A/orgs",
    "repos_url": "https://api.github.com/users/A/repos",
    "events_url": "https://api.github.com/users/A/events{/privacy}",
    "received_events_url": "https://api.github.com/users/A/received_events",
    "type": "User",
    "site_admin": false,
    "score": 1077.4093
  },
  {
    "login": "snyff",
    "id": 45491,
    "node_id": "MDQ6VXNlcjQ1NDkx",
    "avatar_url": "https://avatars1.githubusercontent.com/u/45491?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/snyff",
    "html_url": "https://github.com/snyff",
    "followers_url": "https://api.github.com/users/snyff/followers",
    "following_url": "https://api.github.com/users/snyff/following{/other_user}",
    "gists_url": "https://api.github.com/users/snyff/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/snyff/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/snyff/subscriptions",
    "organizations_url": "https://api.github.com/users/snyff/orgs",
    "repos_url": "https://api.github.com/users/snyff/repos",
    "events_url": "https://api.github.com/users/snyff/events{/privacy}",
    "received_events_url": "https://api.github.com/users/snyff/received_events",
    "type": "User",
    "site_admin": false,
    "score": 68.14088
  },
  {
    "login": "adamwiggins",
    "id": 177,
    "node_id": "MDQ6VXNlcjE3Nw==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/177?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adamwiggins",
    "html_url": "https://github.com/adamwiggins",
    "followers_url": "https://api.github.com/users/adamwiggins/followers",
    "following_url": "https://api.github.com/users/adamwiggins/following{/other_user}",
    "gists_url": "https://api.github.com/users/adamwiggins/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adamwiggins/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adamwiggins/subscriptions",
    "organizations_url": "https://api.github.com/users/adamwiggins/orgs",
    "repos_url": "https://api.github.com/users/adamwiggins/repos",
    "events_url": "https://api.github.com/users/adamwiggins/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adamwiggins/received_events",
    "type": "User",
    "site_admin": false,
    "score": 57.53802
  },
  {
    "login": "Amichai",
    "id": 313874,
    "node_id": "MDQ6VXNlcjMxMzg3NA==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/313874?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Amichai",
    "html_url": "https://github.com/Amichai",
    "followers_url": "https://api.github.com/users/Amichai/followers",
    "following_url": "https://api.github.com/users/Amichai/following{/other_user}",
    "gists_url": "https://api.github.com/users/Amichai/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Amichai/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Amichai/subscriptions",
    "organizations_url": "https://api.github.com/users/Amichai/orgs",
    "repos_url": "https://api.github.com/users/Amichai/repos",
    "events_url": "https://api.github.com/users/Amichai/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Amichai/received_events",
    "type": "User",
    "site_admin": false,
    "score": 57.201286
  },
  {
    "login": "adulau",
    "id": 3309,
    "node_id": "MDQ6VXNlcjMzMDk=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/3309?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adulau",
    "html_url": "https://github.com/adulau",
    "followers_url": "https://api.github.com/users/adulau/followers",
    "following_url": "https://api.github.com/users/adulau/following{/other_user}",
    "gists_url": "https://api.github.com/users/adulau/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adulau/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adulau/subscriptions",
    "organizations_url": "https://api.github.com/users/adulau/orgs",
    "repos_url": "https://api.github.com/users/adulau/repos",
    "events_url": "https://api.github.com/users/adulau/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adulau/received_events",
    "type": "User",
    "site_admin": false,
    "score": 56.474182
  },
  {
    "login": "ngs",
    "id": 18631,
    "node_id": "MDQ6VXNlcjE4NjMx",
    "avatar_url": "https://avatars0.githubusercontent.com/u/18631?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ngs",
    "html_url": "https://github.com/ngs",
    "followers_url": "https://api.github.com/users/ngs/followers",
    "following_url": "https://api.github.com/users/ngs/following{/other_user}",
    "gists_url": "https://api.github.com/users/ngs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ngs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ngs/subscriptions",
    "organizations_url": "https://api.github.com/users/ngs/orgs",
    "repos_url": "https://api.github.com/users/ngs/repos",
    "events_url": "https://api.github.com/users/ngs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ngs/received_events",
    "type": "User",
    "site_admin": false,
    "score": 54.384914
  },
  {
    "login": "iizvv",
    "id": 15830996,
    "node_id": "MDQ6VXNlcjE1ODMwOTk2",
    "avatar_url": "https://avatars3.githubusercontent.com/u/15830996?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/iizvv",
    "html_url": "https://github.com/iizvv",
    "followers_url": "https://api.github.com/users/iizvv/followers",
    "following_url": "https://api.github.com/users/iizvv/following{/other_user}",
    "gists_url": "https://api.github.com/users/iizvv/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/iizvv/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/iizvv/subscriptions",
    "organizations_url": "https://api.github.com/users/iizvv/orgs",
    "repos_url": "https://api.github.com/users/iizvv/repos",
    "events_url": "https://api.github.com/users/iizvv/events{/privacy}",
    "received_events_url": "https://api.github.com/users/iizvv/received_events",
    "type": "User",
    "site_admin": false,
    "score": 52.169216
  },
  {
    "login": "aarizaq",
    "id": 62071,
    "node_id": "MDQ6VXNlcjYyMDcx",
    "avatar_url": "https://avatars1.githubusercontent.com/u/62071?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aarizaq",
    "html_url": "https://github.com/aarizaq",
    "followers_url": "https://api.github.com/users/aarizaq/followers",
    "following_url": "https://api.github.com/users/aarizaq/following{/other_user}",
    "gists_url": "https://api.github.com/users/aarizaq/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aarizaq/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aarizaq/subscriptions",
    "organizations_url": "https://api.github.com/users/aarizaq/orgs",
    "repos_url": "https://api.github.com/users/aarizaq/repos",
    "events_url": "https://api.github.com/users/aarizaq/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aarizaq/received_events",
    "type": "User",
    "site_admin": false,
    "score": 51.731308
  },
  {
    "login": "joshhartigan",
    "id": 5961708,
    "node_id": "MDQ6VXNlcjU5NjE3MDg=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/5961708?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/joshhartigan",
    "html_url": "https://github.com/joshhartigan",
    "followers_url": "https://api.github.com/users/joshhartigan/followers",
    "following_url": "https://api.github.com/users/joshhartigan/following{/other_user}",
    "gists_url": "https://api.github.com/users/joshhartigan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/joshhartigan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/joshhartigan/subscriptions",
    "organizations_url": "https://api.github.com/users/joshhartigan/orgs",
    "repos_url": "https://api.github.com/users/joshhartigan/repos",
    "events_url": "https://api.github.com/users/joshhartigan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/joshhartigan/received_events",
    "type": "User",
    "site_admin": false,
    "score": 51.497593
  },
  {
    "login": "xxczaki",
    "id": 22645979,
    "node_id": "MDQ6VXNlcjIyNjQ1OTc5",
    "avatar_url": "https://avatars3.githubusercontent.com/u/22645979?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/xxczaki",
    "html_url": "https://github.com/xxczaki",
    "followers_url": "https://api.github.com/users/xxczaki/followers",
    "following_url": "https://api.github.com/users/xxczaki/following{/other_user}",
    "gists_url": "https://api.github.com/users/xxczaki/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/xxczaki/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/xxczaki/subscriptions",
    "organizations_url": "https://api.github.com/users/xxczaki/orgs",
    "repos_url": "https://api.github.com/users/xxczaki/repos",
    "events_url": "https://api.github.com/users/xxczaki/events{/privacy}",
    "received_events_url": "https://api.github.com/users/xxczaki/received_events",
    "type": "User",
    "site_admin": false,
    "score": 51.400497
  },
  {
    "login": "tuzimoe",
    "id": 17731805,
    "node_id": "MDQ6VXNlcjE3NzMxODA1",
    "avatar_url": "https://avatars1.githubusercontent.com/u/17731805?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tuzimoe",
    "html_url": "https://github.com/tuzimoe",
    "followers_url": "https://api.github.com/users/tuzimoe/followers",
    "following_url": "https://api.github.com/users/tuzimoe/following{/other_user}",
    "gists_url": "https://api.github.com/users/tuzimoe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tuzimoe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tuzimoe/subscriptions",
    "organizations_url": "https://api.github.com/users/tuzimoe/orgs",
    "repos_url": "https://api.github.com/users/tuzimoe/repos",
    "events_url": "https://api.github.com/users/tuzimoe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tuzimoe/received_events",
    "type": "User",
    "site_admin": false,
    "score": 51.177025
  },
  {
    "login": "AHXR",
    "id": 27564220,
    "node_id": "MDQ6VXNlcjI3NTY0MjIw",
    "avatar_url": "https://avatars2.githubusercontent.com/u/27564220?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AHXR",
    "html_url": "https://github.com/AHXR",
    "followers_url": "https://api.github.com/users/AHXR/followers",
    "following_url": "https://api.github.com/users/AHXR/following{/other_user}",
    "gists_url": "https://api.github.com/users/AHXR/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AHXR/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AHXR/subscriptions",
    "organizations_url": "https://api.github.com/users/AHXR/orgs",
    "repos_url": "https://api.github.com/users/AHXR/repos",
    "events_url": "https://api.github.com/users/AHXR/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AHXR/received_events",
    "type": "User",
    "site_admin": false,
    "score": 50.832333
  },
  {
    "login": "prodigeni",
    "id": 1476070,
    "node_id": "MDQ6VXNlcjE0NzYwNzA=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/1476070?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/prodigeni",
    "html_url": "https://github.com/prodigeni",
    "followers_url": "https://api.github.com/users/prodigeni/followers",
    "following_url": "https://api.github.com/users/prodigeni/following{/other_user}",
    "gists_url": "https://api.github.com/users/prodigeni/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/prodigeni/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/prodigeni/subscriptions",
    "organizations_url": "https://api.github.com/users/prodigeni/orgs",
    "repos_url": "https://api.github.com/users/prodigeni/repos",
    "events_url": "https://api.github.com/users/prodigeni/events{/privacy}",
    "received_events_url": "https://api.github.com/users/prodigeni/received_events",
    "type": "User",
    "site_admin": false,
    "score": 50.80844
  },
  {
    "login": "Saqoosha",
    "id": 27694,
    "node_id": "MDQ6VXNlcjI3Njk0",
    "avatar_url": "https://avatars3.githubusercontent.com/u/27694?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Saqoosha",
    "html_url": "https://github.com/Saqoosha",
    "followers_url": "https://api.github.com/users/Saqoosha/followers",
    "following_url": "https://api.github.com/users/Saqoosha/following{/other_user}",
    "gists_url": "https://api.github.com/users/Saqoosha/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Saqoosha/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Saqoosha/subscriptions",
    "organizations_url": "https://api.github.com/users/Saqoosha/orgs",
    "repos_url": "https://api.github.com/users/Saqoosha/repos",
    "events_url": "https://api.github.com/users/Saqoosha/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Saqoosha/received_events",
    "type": "User",
    "site_admin": false,
    "score": 49.35321
  },
  {
    "login": "kkmonlee",
    "id": 6388711,
    "node_id": "MDQ6VXNlcjYzODg3MTE=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/6388711?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kkmonlee",
    "html_url": "https://github.com/kkmonlee",
    "followers_url": "https://api.github.com/users/kkmonlee/followers",
    "following_url": "https://api.github.com/users/kkmonlee/following{/other_user}",
    "gists_url": "https://api.github.com/users/kkmonlee/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kkmonlee/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kkmonlee/subscriptions",
    "organizations_url": "https://api.github.com/users/kkmonlee/orgs",
    "repos_url": "https://api.github.com/users/kkmonlee/repos",
    "events_url": "https://api.github.com/users/kkmonlee/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kkmonlee/received_events",
    "type": "User",
    "site_admin": false,
    "score": 49.23006
  },
  {
    "login": "ufoym",
    "id": 2270240,
    "node_id": "MDQ6VXNlcjIyNzAyNDA=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/2270240?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ufoym",
    "html_url": "https://github.com/ufoym",
    "followers_url": "https://api.github.com/users/ufoym/followers",
    "following_url": "https://api.github.com/users/ufoym/following{/other_user}",
    "gists_url": "https://api.github.com/users/ufoym/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ufoym/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ufoym/subscriptions",
    "organizations_url": "https://api.github.com/users/ufoym/orgs",
    "repos_url": "https://api.github.com/users/ufoym/repos",
    "events_url": "https://api.github.com/users/ufoym/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ufoym/received_events",
    "type": "User",
    "site_admin": false,
    "score": 48.855854
  },
  {
    "login": "machinaut",
    "id": 79779,
    "node_id": "MDQ6VXNlcjc5Nzc5",
    "avatar_url": "https://avatars3.githubusercontent.com/u/79779?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/machinaut",
    "html_url": "https://github.com/machinaut",
    "followers_url": "https://api.github.com/users/machinaut/followers",
    "following_url": "https://api.github.com/users/machinaut/following{/other_user}",
    "gists_url": "https://api.github.com/users/machinaut/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/machinaut/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/machinaut/subscriptions",
    "organizations_url": "https://api.github.com/users/machinaut/orgs",
    "repos_url": "https://api.github.com/users/machinaut/repos",
    "events_url": "https://api.github.com/users/machinaut/events{/privacy}",
    "received_events_url": "https://api.github.com/users/machinaut/received_events",
    "type": "User",
    "site_admin": false,
    "score": 48.259594
  },
  {
    "login": "austinkelleher",
    "id": 3771924,
    "node_id": "MDQ6VXNlcjM3NzE5MjQ=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/3771924?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/austinkelleher",
    "html_url": "https://github.com/austinkelleher",
    "followers_url": "https://api.github.com/users/austinkelleher/followers",
    "following_url": "https://api.github.com/users/austinkelleher/following{/other_user}",
    "gists_url": "https://api.github.com/users/austinkelleher/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/austinkelleher/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/austinkelleher/subscriptions",
    "organizations_url": "https://api.github.com/users/austinkelleher/orgs",
    "repos_url": "https://api.github.com/users/austinkelleher/repos",
    "events_url": "https://api.github.com/users/austinkelleher/events{/privacy}",
    "received_events_url": "https://api.github.com/users/austinkelleher/received_events",
    "type": "User",
    "site_admin": false,
    "score": 48.04405
  },
  {
    "login": "noidontdig",
    "id": 1229810,
    "node_id": "MDQ6VXNlcjEyMjk4MTA=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1229810?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/noidontdig",
    "html_url": "https://github.com/noidontdig",
    "followers_url": "https://api.github.com/users/noidontdig/followers",
    "following_url": "https://api.github.com/users/noidontdig/following{/other_user}",
    "gists_url": "https://api.github.com/users/noidontdig/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/noidontdig/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/noidontdig/subscriptions",
    "organizations_url": "https://api.github.com/users/noidontdig/orgs",
    "repos_url": "https://api.github.com/users/noidontdig/repos",
    "events_url": "https://api.github.com/users/noidontdig/events{/privacy}",
    "received_events_url": "https://api.github.com/users/noidontdig/received_events",
    "type": "User",
    "site_admin": false,
    "score": 47.81964
  },
  {
    "login": "liuwons",
    "id": 9864950,
    "node_id": "MDQ6VXNlcjk4NjQ5NTA=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/9864950?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/liuwons",
    "html_url": "https://github.com/liuwons",
    "followers_url": "https://api.github.com/users/liuwons/followers",
    "following_url": "https://api.github.com/users/liuwons/following{/other_user}",
    "gists_url": "https://api.github.com/users/liuwons/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/liuwons/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/liuwons/subscriptions",
    "organizations_url": "https://api.github.com/users/liuwons/orgs",
    "repos_url": "https://api.github.com/users/liuwons/repos",
    "events_url": "https://api.github.com/users/liuwons/events{/privacy}",
    "received_events_url": "https://api.github.com/users/liuwons/received_events",
    "type": "User",
    "site_admin": false,
    "score": 47.78732
  },
  {
    "login": "carsonoid",
    "id": 2973513,
    "node_id": "MDQ6VXNlcjI5NzM1MTM=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/2973513?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/carsonoid",
    "html_url": "https://github.com/carsonoid",
    "followers_url": "https://api.github.com/users/carsonoid/followers",
    "following_url": "https://api.github.com/users/carsonoid/following{/other_user}",
    "gists_url": "https://api.github.com/users/carsonoid/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/carsonoid/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/carsonoid/subscriptions",
    "organizations_url": "https://api.github.com/users/carsonoid/orgs",
    "repos_url": "https://api.github.com/users/carsonoid/repos",
    "events_url": "https://api.github.com/users/carsonoid/events{/privacy}",
    "received_events_url": "https://api.github.com/users/carsonoid/received_events",
    "type": "User",
    "site_admin": false,
    "score": 47.203735
  },
  {
    "login": "antiface",
    "id": 1619852,
    "node_id": "MDQ6VXNlcjE2MTk4NTI=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/1619852?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/antiface",
    "html_url": "https://github.com/antiface",
    "followers_url": "https://api.github.com/users/antiface/followers",
    "following_url": "https://api.github.com/users/antiface/following{/other_user}",
    "gists_url": "https://api.github.com/users/antiface/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/antiface/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/antiface/subscriptions",
    "organizations_url": "https://api.github.com/users/antiface/orgs",
    "repos_url": "https://api.github.com/users/antiface/repos",
    "events_url": "https://api.github.com/users/antiface/events{/privacy}",
    "received_events_url": "https://api.github.com/users/antiface/received_events",
    "type": "User",
    "site_admin": false,
    "score": 47.137547
  },
  {
    "login": "Alwahsh",
    "id": 3496597,
    "node_id": "MDQ6VXNlcjM0OTY1OTc=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/3496597?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Alwahsh",
    "html_url": "https://github.com/Alwahsh",
    "followers_url": "https://api.github.com/users/Alwahsh/followers",
    "following_url": "https://api.github.com/users/Alwahsh/following{/other_user}",
    "gists_url": "https://api.github.com/users/Alwahsh/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Alwahsh/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Alwahsh/subscriptions",
    "organizations_url": "https://api.github.com/users/Alwahsh/orgs",
    "repos_url": "https://api.github.com/users/Alwahsh/repos",
    "events_url": "https://api.github.com/users/Alwahsh/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Alwahsh/received_events",
    "type": "User",
    "site_admin": false,
    "score": 47.014053
  },
  {
    "login": "maruel",
    "id": 75011,
    "node_id": "MDQ6VXNlcjc1MDEx",
    "avatar_url": "https://avatars2.githubusercontent.com/u/75011?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/maruel",
    "html_url": "https://github.com/maruel",
    "followers_url": "https://api.github.com/users/maruel/followers",
    "following_url": "https://api.github.com/users/maruel/following{/other_user}",
    "gists_url": "https://api.github.com/users/maruel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/maruel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/maruel/subscriptions",
    "organizations_url": "https://api.github.com/users/maruel/orgs",
    "repos_url": "https://api.github.com/users/maruel/repos",
    "events_url": "https://api.github.com/users/maruel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/maruel/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.8446
  },
  {
    "login": "andydbc",
    "id": 31256170,
    "node_id": "MDQ6VXNlcjMxMjU2MTcw",
    "avatar_url": "https://avatars1.githubusercontent.com/u/31256170?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/andydbc",
    "html_url": "https://github.com/andydbc",
    "followers_url": "https://api.github.com/users/andydbc/followers",
    "following_url": "https://api.github.com/users/andydbc/following{/other_user}",
    "gists_url": "https://api.github.com/users/andydbc/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/andydbc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/andydbc/subscriptions",
    "organizations_url": "https://api.github.com/users/andydbc/orgs",
    "repos_url": "https://api.github.com/users/andydbc/repos",
    "events_url": "https://api.github.com/users/andydbc/events{/privacy}",
    "received_events_url": "https://api.github.com/users/andydbc/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.69556
  },
  {
    "login": "zedshaw",
    "id": 358171,
    "node_id": "MDQ6VXNlcjM1ODE3MQ==",
    "avatar_url": "https://avatars2.githubusercontent.com/u/358171?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zedshaw",
    "html_url": "https://github.com/zedshaw",
    "followers_url": "https://api.github.com/users/zedshaw/followers",
    "following_url": "https://api.github.com/users/zedshaw/following{/other_user}",
    "gists_url": "https://api.github.com/users/zedshaw/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zedshaw/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zedshaw/subscriptions",
    "organizations_url": "https://api.github.com/users/zedshaw/orgs",
    "repos_url": "https://api.github.com/users/zedshaw/repos",
    "events_url": "https://api.github.com/users/zedshaw/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zedshaw/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.647827
  },
  {
    "login": "Curzibn",
    "id": 4538051,
    "node_id": "MDQ6VXNlcjQ1MzgwNTE=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/4538051?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Curzibn",
    "html_url": "https://github.com/Curzibn",
    "followers_url": "https://api.github.com/users/Curzibn/followers",
    "following_url": "https://api.github.com/users/Curzibn/following{/other_user}",
    "gists_url": "https://api.github.com/users/Curzibn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Curzibn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Curzibn/subscriptions",
    "organizations_url": "https://api.github.com/users/Curzibn/orgs",
    "repos_url": "https://api.github.com/users/Curzibn/repos",
    "events_url": "https://api.github.com/users/Curzibn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Curzibn/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.48573
  },
  {
    "login": "schachmat",
    "id": 2626530,
    "node_id": "MDQ6VXNlcjI2MjY1MzA=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/2626530?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/schachmat",
    "html_url": "https://github.com/schachmat",
    "followers_url": "https://api.github.com/users/schachmat/followers",
    "following_url": "https://api.github.com/users/schachmat/following{/other_user}",
    "gists_url": "https://api.github.com/users/schachmat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/schachmat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/schachmat/subscriptions",
    "organizations_url": "https://api.github.com/users/schachmat/orgs",
    "repos_url": "https://api.github.com/users/schachmat/repos",
    "events_url": "https://api.github.com/users/schachmat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/schachmat/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.39968
  },
  {
    "login": "keesun",
    "id": 463657,
    "node_id": "MDQ6VXNlcjQ2MzY1Nw==",
    "avatar_url": "https://avatars1.githubusercontent.com/u/463657?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/keesun",
    "html_url": "https://github.com/keesun",
    "followers_url": "https://api.github.com/users/keesun/followers",
    "following_url": "https://api.github.com/users/keesun/following{/other_user}",
    "gists_url": "https://api.github.com/users/keesun/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/keesun/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/keesun/subscriptions",
    "organizations_url": "https://api.github.com/users/keesun/orgs",
    "repos_url": "https://api.github.com/users/keesun/repos",
    "events_url": "https://api.github.com/users/keesun/events{/privacy}",
    "received_events_url": "https://api.github.com/users/keesun/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.37766
  },
  {
    "login": "astronomersiva",
    "id": 7725225,
    "node_id": "MDQ6VXNlcjc3MjUyMjU=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/7725225?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/astronomersiva",
    "html_url": "https://github.com/astronomersiva",
    "followers_url": "https://api.github.com/users/astronomersiva/followers",
    "following_url": "https://api.github.com/users/astronomersiva/following{/other_user}",
    "gists_url": "https://api.github.com/users/astronomersiva/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/astronomersiva/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/astronomersiva/subscriptions",
    "organizations_url": "https://api.github.com/users/astronomersiva/orgs",
    "repos_url": "https://api.github.com/users/astronomersiva/repos",
    "events_url": "https://api.github.com/users/astronomersiva/events{/privacy}",
    "received_events_url": "https://api.github.com/users/astronomersiva/received_events",
    "type": "User",
    "site_admin": false,
    "score": 46.307312
  }
]

module.exports = USERS
